### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by artpolikarpov** [chatr/desktop#30]
One of our user faced «installation has failed» error.

Screenshot:
https://gyazo.com/786a7e9915971b0f61c0f47399bd34e4

And the log:
```
2016-04-08 09:50:28> Program: Starting Squirrel Updater: --install .

2016-04-08 09:50:28> Program: Starting install, writing to C:\Users\Scott\AppData\Local\SquirrelTemp

2016-04-08 09:50:28> Program: About to install to: C:\Users\Scott\AppData\Local\chatra

2016-04-08 09:50:28> Program: Install path C:\Users\Scott\AppData\Local\chatra already exists, burning it to the ground

2016-04-08 09:50:28> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.IO.IOException: The process cannot access the file 'C:\Users\Scott\AppData\Local\chatra\cookies' because it is being used by another process.

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

at System.IO.File.InternalDelete(String path, Boolean checkHost)

at System.IO.File.Delete(String path)

at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)

at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()

at System.Threading.Tasks.Task.InnerInvoke()

at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()

2016-04-08 09:50:28> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'C:\Users\Scott\AppData\Local\chatra\cookies' because it is being used by another process.

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

at System.IO.File.InternalDelete(String path, Boolean checkHost)

at System.IO.File.Delete(String path)

at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)

at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()

at System.Threading.Tasks.Task.InnerInvoke()

at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Update.Program.<Install>d__4.MoveNext()

--- End of inner exception stack trace ---

at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)

at System.Threading.Tasks.Task.Wait()

at Squirrel.Update.Program.executeCommandLine(String[] args)

at Squirrel.Update.Program.main(String[] args)

---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Users\Scott\AppData\Local\chatra\cookies' because it is being used by another process.

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

at System.IO.File.InternalDelete(String path, Boolean checkHost)

at System.IO.File.Delete(String path)

at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)

at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()

at System.Threading.Tasks.Task.InnerInvoke()

at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Update.Program.<Install>d__4.MoveNext()<---



2016-04-08 09:50:38> Program: Starting Squirrel Updater: --install .

2016-04-08 09:50:38> Program: Starting install, writing to C:\Users\Scott\AppData\Local\SquirrelTemp

2016-04-08 09:50:38> Program: About to install to: C:\Users\Scott\AppData\Local\chatra

2016-04-08 09:50:38> Program: Install path C:\Users\Scott\AppData\Local\chatra already exists, burning it to the ground

2016-04-08 09:50:38> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.IO.IOException: The process cannot access the file 'C:\Users\Scott\AppData\Local\chatra\cookies' because it is being used by another process.

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

at System.IO.File.InternalDelete(String path, Boolean checkHost)

at System.IO.File.Delete(String path)

at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)

at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()

at System.Threading.Tasks.Task.InnerInvoke()

at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()

2016-04-08 09:50:38> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'C:\Users\Scott\AppData\Local\chatra\cookies' because it is being used by another process.

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

at System.IO.File.InternalDelete(String path, Boolean checkHost)

at System.IO.File.Delete(String path)

at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)

at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()

at System.Threading.Tasks.Task.InnerInvoke()

at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Update.Program.<Install>d__4.MoveNext()

--- End of inner exception stack trace ---

at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)

at System.Threading.Tasks.Task.Wait()

at Squirrel.Update.Program.executeCommandLine(String[] args)

at Squirrel.Update.Program.main(String[] args)

---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Users\Scott\AppData\Local\chatra\cookies' because it is being used by another process.

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

at System.IO.File.InternalDelete(String path, Boolean checkHost)

at System.IO.File.Delete(String path)

at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)

at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()

at System.Threading.Tasks.Task.InnerInvoke()

at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Update.Program.<Install>d__4.MoveNext()<---



2016-04-08 10:31:21> Program: Starting Squirrel Updater: --install .

2016-04-08 10:31:21> Program: Starting install, writing to C:\Users\Scott\AppData\Local\SquirrelTemp

2016-04-08 10:31:21> Program: About to install to: C:\Users\Scott\AppData\Local\chatra

2016-04-08 10:31:21> Program: Install path C:\Users\Scott\AppData\Local\chatra already exists, burning it to the ground

2016-04-08 10:31:21> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.IO.IOException: The process cannot access the file 'C:\Users\Scott\AppData\Local\chatra\cookies' because it is being used by another process.

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

at System.IO.File.InternalDelete(String path, Boolean checkHost)

at System.IO.File.Delete(String path)

at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)

at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()

at System.Threading.Tasks.Task.InnerInvoke()

at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()

2016-04-08 10:31:21> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'C:\Users\Scott\AppData\Local\chatra\cookies' because it is being used by another process.

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

at System.IO.File.InternalDelete(String path, Boolean checkHost)

at System.IO.File.Delete(String path)

at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)

at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()

at System.Threading.Tasks.Task.InnerInvoke()

at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Update.Program.<Install>d__4.MoveNext()

--- End of inner exception stack trace ---

at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)

at System.Threading.Tasks.Task.Wait()

at Squirrel.Update.Program.executeCommandLine(String[] args)

at Squirrel.Update.Program.main(String[] args)

---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Users\Scott\AppData\Local\chatra\cookies' because it is being used by another process.

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

at System.IO.File.InternalDelete(String path, Boolean checkHost)

at System.IO.File.Delete(String path)

at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)

at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()

at System.Threading.Tasks.Task.InnerInvoke()

at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Update.Program.<Install>d__4.MoveNext()<---



2016-04-08 11:05:12> Program: Starting Squirrel Updater: --install .

2016-04-08 11:05:12> Program: Starting install, writing to C:\Users\Scott\AppData\Local\SquirrelTemp

2016-04-08 11:05:12> Program: About to install to: C:\Users\Scott\AppData\Local\chatra

2016-04-08 11:05:12> Program: Install path C:\Users\Scott\AppData\Local\chatra already exists, burning it to the ground

2016-04-08 11:05:12> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.IO.IOException: The process cannot access the file 'C:\Users\Scott\AppData\Local\chatra\lockfile' because it is being used by another process.

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

at System.IO.File.InternalDelete(String path, Boolean checkHost)

at System.IO.File.Delete(String path)

at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)

at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()

at System.Threading.Tasks.Task.InnerInvoke()

at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()

2016-04-08 11:05:12> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'C:\Users\Scott\AppData\Local\chatra\lockfile' because it is being used by another process.

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

at System.IO.File.InternalDelete(String path, Boolean checkHost)

at System.IO.File.Delete(String path)

at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)

at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()

at System.Threading.Tasks.Task.InnerInvoke()

at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Update.Program.<Install>d__4.MoveNext()

--- End of inner exception stack trace ---

at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)

at System.Threading.Tasks.Task.Wait()

at Squirrel.Update.Program.executeCommandLine(String[] args)

at Squirrel.Update.Program.main(String[] args)

---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Users\Scott\AppData\Local\chatra\lockfile' because it is being used by another process.

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

at System.IO.File.InternalDelete(String path, Boolean checkHost)

at System.IO.File.Delete(String path)

at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)

at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()

at System.Threading.Tasks.Task.InnerInvoke()

at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

at Squirrel.Update.Program.<Install>d__4.MoveNext()<---
```

**Comment by Aluxian** [comment]
From the log, it seems the installer failed because the old Chatra app was still running. I'm afraid I can't do anything about this since this would require rebuilding the entire Squirrel.Windows framework in order to add some code to kill the old app first.

**Comment by artpolikarpov** [comment]
Ok!
